config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  #limit routes to only these 4
  resources :messages, :only => [:index, :new, :create, :show]
  resources :users, :only => [:show]

  root :to => 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :users

end

app/models/message.rb
class Message < ActiveRecord::Base
  before_create :send_sms

private
  def send_sms
    begin
    response = RestClient::Request.new(
      :method => :post,
      :url => 'https://api.twilio.com/2010-04-01/Accounts/AC92343d189fc553f58a92f9895da8ced5/Messages.json',
      :user => ENV['Twilio_Acc_Sid'],
      :password => ENV['Twilio_Auth_Token'],
      :payload => { :Body => body,
                    :From => from,
                    :To => to}
    ).execute
    rescue RestClient::BadRequest => error
      message = JSON.parse(error.response)['message']
      errors.add(:base, message)
      throw(:abort) #helping it not crash if it fails to save
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :contacts
  acts_as_votable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:username, :phone, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:sign_in) do |user_params|
      user_params.permit(:username, :phone, :email, :password)
    end
    devise_parameter_sanitizer.permit(:account_update) do |user_params|
      user_params.permit(:username, :phone, :email, :current_password, :password, :password_confirmation)
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

def index
  @users = User.all
  @user2 = User.find_by(params[:id]);
  if params[:upvote]
    @user = User.find(params[:upvote])
    @user.liked_by current_user
  end

#tWEATHER    this makes the weather object and runs get humidity
  weather_object = Weather.new("98683")
  @humidity = weather_object.get_humidity()
end

def new

end

def create

end

def show

end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

def index
  @user = current_user
  @messages = Message.all
end

def create
  @message = Message.new(message_params)
  if @message.save
    flash[:notice] = "Sent!"
    redirect_to messages_path
  else
    render 'new'
  end
end

def show
  @message = Message.find(params[:id])
end

private

 def message_params
   params.require(:message).permit(:to, :from, :body)
 end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    @user2 = User.find(params[:id])
    @message = Message.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>Home</h1>

<ul>
  <% @users.each do |user| %>
    <li><%= user.username %>
       <%= link_to image_tag("star.png"), {:upvote => user.id} %>
       <span class="vote-number"><%= user.get_likes.size %></span>
       <%= link_to "Text now!", user_path(user)  %>
    </li>

  <% end %>


</ul>



<!-- WEATHER humidity runs get humidity -->
  <h1> The current humidity for <%= @zip %>: <%= @humidity %></h1>



<!-- <%= user2 = User.find_by(:username => "Kyle"); %> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwilioRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class = "nav navbar navbar-inverse ">
      <a href="/"><span class="brand">Textilio</span> </a>

        <div class="pull-right shift-login">
        <% if current_user %>
          <span class="glyphicon glyphicon-ok-circle" aria-hidden="true"></span>
          <span class="white"><%= current_user.email %></span> |
          <%= link_to "Log-out", destroy_user_session_path, method: "delete" %>
        <% else %>
          <span class="glyphicon glyphicon-remove-circle" aria-hidden="true"></span>
          <%= link_to "Log-in", new_user_session_path %></a> |
          <%= link_to "Signup", new_user_registration_path %></a>
        <% end %>
      </div>
    </nav>
    <div class="container">
      <%= flash[:notice] %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_form.html.erb
<% if @message.errors.any? %>
  <p>Something went wrong:</p>
  <ul>
    <% @message.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @message do |f| %>
  <%= f.label :to %>
  <%= f.text_field :to, :value => @user2.phone  %> <!-- Current_user's phone number -->
  <%= f.label :from %>
  <%= f.text_field :from, :value => "2085955077" %>
  <%= f.label :body %>
  <%= f.text_field :body, :value => 'Hello' %>
  <%= f.submit %>
<% end  %>

app/views/messages/index.html.erb
<h1>Messages</h1>


<ul>
  <% @messages.each do |message| %>
    <li><%= link_to message.body, message_path(message) %></li>
  <% end %>
</ul>
<%= link_to "Send a new text message", new_message_path %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<% if @message.errors.any? %>
  <p>Something wen wrong:</p>
  <ul>
    <% @message.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @message do |f| %>
  <%= f.label :to %>
  <%= f.text_field :to, :value => @user.phone %> <!-- Current_user's phone number -->
  <%= f.label :from %>
  <%= f.text_field :from, :value => @user2.phone %>
  <%= f.label :body %>
  <%= f.text_field :body, :value => 'Hello' %>
  <%= f.submit %>
<% end  %>
<!-- 2085955077  working number for from -->

app/views/users/show.html.erb
<h1><%= @user2.username %></h1>

<%= render "/messages/form", @message => :message %>